name: CI

on: [push]

jobs:
  build-inventory-import:
    name: Build the application for Inventory import
    runs-on: ubuntu-latest
    env:
      CTP_CLIENT_ID: ${{ secrets.CTP_CLIENT_ID }}
      CTP_CLIENT_SECRET: ${{ secrets.CTP_CLIENT_SECRET }}
      CTP_PROJECT_KEY: ${{ secrets.CTP_PROJECT_KEY }}
      CTP_SCOPE: ${{ secrets.CTP_SCOPE }}
      CTP_REGION: ${{ secrets.CTP_REGION }}
    defaults:
      run:
        working-directory: inventory-import
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install modules
        run: npm ci

      - name: Check the coding style
        run: npm run lint && npm run prettier

      - name: Execute tests
        run: npm run test:ci

  build-order-export:
    name: Build the application for Order Export
    runs-on: ubuntu-latest
    env:
      CTP_CLIENT_ID: ${{ secrets.CTP_CLIENT_ID }}
      CTP_CLIENT_SECRET: ${{ secrets.CTP_CLIENT_SECRET }}
      CTP_PROJECT_KEY: ${{ secrets.CTP_PROJECT_KEY }}
      CTP_SCOPE: ${{ secrets.CTP_SCOPE }}
      CTP_REGION: ${{ secrets.CTP_REGION }}
    defaults:
      run:
        working-directory: order-export
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install modules
        run: npm ci

      - name: Check the coding style
        run: npm run lint && npm run prettier

      - name: Execute tests
        run: npm run test:ci

  build-order-updates:
    name: Build the application for Order updates
    runs-on: ubuntu-latest
    env:
      CTP_CLIENT_ID: ${{ secrets.CTP_CLIENT_ID }}
      CTP_CLIENT_SECRET: ${{ secrets.CTP_CLIENT_SECRET }}
      CTP_PROJECT_KEY: ${{ secrets.CTP_PROJECT_KEY }}
      CTP_SCOPE: ${{ secrets.CTP_SCOPE }}
      CTP_REGION: ${{ secrets.CTP_REGION }}
    defaults:
      run:
        working-directory: order-updates
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install modules
        run: npm ci

      - name: Check the coding style
        run: npm run lint && npm run prettier

      - name: Execute tests
        run: npm run test:ci

  build-product-export:
    name: Build the application for Product Export
    runs-on: ubuntu-latest
    env:
      CTP_CLIENT_ID: ${{ secrets.CTP_CLIENT_ID }}
      CTP_CLIENT_SECRET: ${{ secrets.CTP_CLIENT_SECRET }}
      CTP_PROJECT_KEY: ${{ secrets.CTP_PROJECT_KEY }}
      CTP_SCOPE: ${{ secrets.CTP_SCOPE }}
      CTP_REGION: ${{ secrets.CTP_REGION }}
    defaults:
      run:
        working-directory: product-export
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install modules
        run: npm ci

      - name: Check the coding style
        run: npm run lint && npm run prettier

      - name: Execute tests
        run: npm run test:ci